### ISSUE TITLE
VTS L1 Enhancement - Test Profile Changes - Power Manager

### ISSUE THREAD

**Issue by srinivasgtl** [rdkcentral/rdk-halif-test-power_manager#14] opened 2024-07-22 20:06 UTC
This task is to get the L1 VTS code updated with the new Test profile yml files introduced during VTS L2.

**Comment by akhilbhas** [comment] 2024-07-24 04:31
Closing this issue as it is duplicate of https://github.com/rdkcentral/rdk-halif-test-power_manager/issues/11

**Closed by akhilbhas** 2024-07-24 04:31 UTC
Labels: L1 related issues
